### Model configuration ###

experiment_name: whisp_vocos

dirs:
  logging: vq_vocoder_experiments

seed: 1234

batch:
  type: VocoderBatchProcessor

data_loaders:
  batch_size: { default: 4, debug: 2 }
  epoch_len: { train: 10000, test: ~ }
  min_batch_size: 2
  min_prefetch_factor: { default: 50, debug: 1 }
  max_prefetch_factor: { default: 150, debug: 1 }

trainer:
  accelerator: { default: gpu, debug: cpu }
  devices: { default: [auto], debug: 1 }
  max_steps: 8000000
  accumulate_grad_batches: 1
  limit_val_batches: 100
  log_every_n_steps: 100
  # resume_from_checkpoint: /path/to/checkpoint

checkpoint:
  monitor: val_loss
  filename: vocos_checkpoint_{epoch}_{step}_{val_loss:.4f}
  save_top_k: 3
  save_last: true

callbacks:
  LearningRateMonitor: {}
  ModelSummary: {}
  GradNormCallback: {}

experiment:
  class_name: VocosExp
  init_args:
    sample_rate: 24000
    initial_learning_rate: 5.e-4
    mel_loss_coeff: 5.0
    mrd_loss_coeff: 0.1
    num_warmup_steps: 0  # Optimizers warmup steps
    pretrain_mel_steps: 0  # 0 means GAN objective from the first iteration
    with_cdpam: false
    cdpam_every: 1
    cdpam_device: cuda:0

    # automatic evaluation
    evaluate_utmos: false
    evaluate_pesq: true
    evaluate_periodicty: true

model:
  feature_extractor:
    class_name: AudioFeatures
    init_args:
        input_feat_type: ssl_feat
        ssl_feat_dim: 1024
        encoder_num_layers: 2
        energy_interval: [0, 1.5]  # [0, 150]
        pitch_interval: [0, 1.5]  # [0, 880]
        style_encoder_type: StyleTTS2
        style_feat_type: mel_spectrogram
        style_emb_dim: 128
        style_use_gmvae: false
        use_lang_emb: false
        use_speaker_emb: true
        use_speech_quality_emb: true
        use_style: true
        use_energy: true
        use_pitch: true
        use_plbert: true
        use_averages: true
        use_range: false
        use_sf_encoder: true
        use_vq: false
        vq_num_quantizers: 1
        vq_codebook_size: 256
        use_auxiliary_classification_loss: true
        use_auxiliary_mel_loss: true

  backbone:
    class_name: VocosResNetBackbone
    init_args:
      input_channels: 256
      dim: 1024
      num_blocks: 4
      # intermediate_dim: 1536
      # num_layers: 12

  head:
    class_name: NSFHead
    init_args:
      dim: 1024
      style_emb_dim: 128
