### Data Configuration ###

dirs:
  data_root: &data_root ../../../examples/simple_datasets/speech/SEGS
  dump_folder: &dump_folder dump_vc_whisp_24KHz

file_search:
  ext: .TextGridStage3
  with_subfolders: true

data_server:
  n_processes: { default: 6, debug: 1 }
  # n_gpus: 1

dataset:
  subsets: [train, test]
  split_type: auto  # auto, manual
  split_ratio: { default: 0.999, debug: 0.5 }
  max_num_samples: { default: 0, debug: 40 }
  directory_filter:
    include: { default: ~, ru: RU, en: EN }
    exclude: ["!"]

parser:
  type: TTSDSParser
  dump:
    default: !join [*data_root, *dump_folder]  # fast dataset load
    debug: ~
  pipe: [audio_strip, split_by_phrases, check_phoneme_length, get_simple_intonation_type]
  pipe_cfg:
    audio_strip:
      pad: 0.25
      add_fade: true
    split_by_phrases:
      max_duration: 10  # 10, 12, 15
    check_phoneme_length:
      max_len: 0.4
    get_simple_intonation_type:
      punctuation_marks: [".", "?"]

preproc:
  pipe: [load_audio, load_text_from_sega,
         voice_bio, speech_quality,
         spectrogram, melscale,
         energy, pitch, enhancement_energy, enhancement_pitch,
         average_by_time, norm,
         add_pauses_from_timestamps, text,
         int_durations, calc_invert_durations, transcription_by_frames, float_durations,
         ssl, plbert,
         to_whisper, ssl,
         load_audio, trim, mu_law]
  pipe_cfg:
    load_audio:
      type: SignalProcessor
      pipe: [load]
      pipe_cfg:
        load:
          sample_rate: 24000
    voice_bio:
      type: VoiceBiometricProcessor
      model_type: wespeaker
      max_audio_duration: 5
      random_crop: true
    speech_quality:
      type: SpeechQualityAssessment
    spectrogram:
      type: SpectralProcessor
      pipe: [magnitude]
      pipe_cfg:
        magnitude:
          n_fft: 1024
          hop_len: 320
          win_len: 1024
    melscale:
      type: MelProcessor
      pipe: [linear_to_mel, amp_to_db, normalize]
      pipe_cfg:
        linear_to_mel:
          n_mels: 80
          f_min: 0
          f_max: 8000
    energy:
      type: SpectralProcessor
      pipe: [energy]
    pitch:
      type: PitchProcessor
      method: pyworld
    enhancement_energy:
      type: signal_enhancement
      attributes: energy
      smooth: true
    enhancement_pitch:
      type: signal_enhancement
      attributes: pitch
      smooth: true
    average_by_time:
      attributes: [energy, pitch]
      use_quantile: true
    norm:
      type: normalize
      attributes: [energy, pitch]
      normalize_by: sample
      method: quantile
      filter_outliers: true
      min_value: 0
    add_pauses_from_timestamps:
      step: 0.05
    text:
      type: TextProcessor
      lang: MULTILANG
    int_durations:
      type: calc_durations
      as_int: true
    calc_invert_durations:
      token_level: true
    float_durations:
      type: calc_durations
      as_int: False
    to_whisper:
      type: SignalProcessor
      pipe: [whisper]
      pipe_cfg:
        whisper:
          p: 0.5
    ssl:
      type: SSLProcessor
      ssl_type: Hubert
      ssl_params:
        # feature_type: centroids
        model_name: facebook/hubert-large-ls960-ft
        pretrain_path: hubert_phoneme_en/epoch=0-step=4500.ckpt
        vocab_path: hubert_phoneme_en/vocab.json
        # stream_mod:
        #   chunk_size: 6400
        #   context_size: [64000, 6550]
    plbert:
      type: MultilingualPLBert
      from_ssl_tokens: True
    timedim_interpolation:
      features: [ssl_feat, plbert_feat]
      shape_as: mel
    trim:
      type: SignalProcessor
      pipe: [trim]
      pipe_cfg:
        trim:
          random_chunk: true
          num_samples_per_chunk: 40960  # 40952 for DAC head
    mu_law:
      type: SignalProcessor
      pipe: [mu_law_encode]

singleton_handlers:
  handlers: [SpeakerIDSetter]
  SpeakerIDSetter: {}
  StatisticsRange:
    statistics_file: !join [*data_root, *dump_folder, ranges.json]

collate:
  type: TTSCollate
  # multiple:
  #   spectrogram: 16
  #   ssl_feat: 16
  #   plbert_feat: 16

processor:
  type: DataProcessor
  output_collated_only: true
  dump:
    default:
      data_root: *data_root
      folder_path: !join [*data_root, *dump_folder]
      fields: [file_path, speaker_name]
      functions: [VoiceBiometricProcessor, SpeechQualityAssessment,
                  PitchProcessor, SSLProcessor, MultilingualPLBert]
      mode: file_path
      skip_samples_without_dump: true
    debug: ~

sampler:
  train:
    type: RandomSampler
  test:
    type: SimpleSampler
