
dirs:
  data_root: &data_root /data
  dump_folder: &dump_folder dump_prosody

file_search:
  ext: .TextGrid_prosody
  with_subfolders: True

data_server:
  n_processes: { default: 1, debug: 1 }


dataset:
  subsets: [train, test]
  split_type: auto
  split_ratio: { default: 0.9, debug: 0.5 }
  max_num_samples: { default: 0, debug: 100 }

parser:
  type: ProsodyParser
  dump: !join [*data_root, *dump_folder]
  tokenizer_name:
    default: data/common/xlm-roberta-large/tokenizer,
    ru: data/ru/homo_classifier/tokenizer,
    en: data/en/roberta_large/tokenizer,
    ml: data/common/xlm-roberta-large/tokenizer,
  pipe: [combine_texts, check_prosody_tags]

collate:
  type: ProsodyPredictionCollate

processor:
  type: DataProcessor
  output_collated_only: True
  verbose_logging: True

sampler:
  train:
    type: WeightedSampler
    comb_by_len: True
    epoch_size: 15000
    fields_to_compute_weight: [category]
    filter_tags: [-100]
    is_sequence: [category]
  test:
    type: SimpleSampler
    comb_by_len: True
