### Model configuration ###

experiment_name: forced_alignment_stage2

dirs:
  logging: glowtts_2stage

seed: 1234

data_loaders:
  batch_size: 32

batch:
  type: AlignerBatchProcessor

trainer:
  accelerator: gpu
  devices: [auto]
  max_epochs: 100
  gradient_clip_val: 5.0
  accumulate_grad_batches: 1
  # precision: 16

checkpoint:
  monitor: Epoch
  mode: max
  save_top_k: 5
  every_n_epochs: 5

optimizer:
  method:
    type: AdamW
    weight_decay: 1.e-6
  lr_scheduler:
    type: ConstLR
    lr_max: 1.e-4

loss:
  type: GlowTTSLoss

net:
  type: GlowTTS
  params:
    audio_feat: mel
    audio_feat_size: 100
    token_emb_dim: 128
    speaker_emb_dim: 128
    encoder_embedding_dim: 128
    inner_channels_enc: 256
    inner_channels_dec: 512

    use_dnn_speaker_emb: true
    speaker_biometric_model: wespeaker

    # use_alignment_encoder: true
    # alignment_encoder_temperature: 15.0
    # alignment_encoder_dist_type: cosine

    # use_mas_correction: true
