site_name: TTS Research

markdown_extensions:
  - admonition

theme: readthedocs

nav:
- Home: index.md
- Настройка окружения:
  - Singularity: env/singularity.md
- Аннотирование аудиокниг:
  - Обзор: annotator/overview.md
  - AudioTranscription: annotator/audio_transcription.md
  - AudiobookSpliter: annotator/audiobook_spliter.md
  - Alignment: annotator/align.md
- Фонемизатор:
  - Описание фонем: phonemes/phonemes.md
- Аугментации:
  - Описание: augmentations/augmentations.md
- MNIST:
  - Обзор: MNIST/overview.md
  - Сервер данных: MNIST/DataServer.md
  - Загрузка базы данных: MNIST/DSParser.md
  - Препроцессинг данных: MNIST/DataProcessor.md
  - Имплементация модели: MNIST/Model.md
  - Запуск обучения: MNIST/train.md
- Keyword Spotter:
    - Обзор: spotter/overview.md
- Vocoders:
    - Обучение на синтезированных спектрах: vocoders/synth_train.md
    - Дата-классы: vocoders/data_classes.md
    - Препроцессинг данных: vocoders/data_preprocessing.md
    - Батч-процессоры и фазы обучения: vocoders/batch_processors.md
    - Callbacks: vocoders/callbacks.md
    - Модели и модули:
        - Структура директорий: vocoders/modules/about.md
        - Common modules:
            - Activations: vocoders/modules/common/activations.md
            - Attention: vocoders/modules/common/attention.md
            - PQMF: vocoders/modules/common/pqmf.md
            - WeightNorm: vocoders/modules/common/wn.md
        - Transforms: vocoders/modules/transforms.md
        - Models:
            - MelGAN: vocoders/modules/models/fftmelgan/generator/generator.md
            - STFT: vocoders/modules/models/fftmelgan/discriminator/stft.md
            - WaveForm: vocoders/modules/models/fftmelgan/discriminator/wf.md
    - Лосс-функции:
      - Интерфейс и базовый класс: vocoders/criterion_modules/base_class.md
      - Имплементированные лосс-функции:
          - STFT loss: vocoders/criterion_modules/avaliable/stft.md
          - LSGAN Adversarial loss: vocoders/criterion_modules/avaliable/ls_gan.md
          - Feature Matching loss: vocoders/criterion_modules/avaliable/fml.md
