
dirs:
#  data_root: &data_root /home/TTS_DATA/multispeaker_data/
# file_list: /home/TTS_DATA/multispeaker_data/manual.txt
  data_root: &data_root /data/
  file_list: /data/pauses_filelist.txt

file_search:
  ext: .TextGridStage2
  with_subfolders: True

data_server:
  n_processes: 0


dataset:
  subsets: [train, test]
  split_type: manual
  # split_ratio:
  #   train: [0.0, 0.98]
  #  test: [0.98, 1.0]
  max_num_samples: 0
  # directory_filter: [Irina, Eugenia, Nikita, Krosh, Ruslan, Tatiana_new, Tatiana_old, CSS10]

parser:
  type: TTSDSParser
  pipe: [wave_strip, split_by_phrases, check_phoneme_length]
  split_by_phrases:
    max_duration: 20
  check_phoneme_length:
    min_len: 0.05
    max_len: 0.4

preproc:
  pipe: [add_pauses_from_timestamps, text, calc_durations]
  add_pauses_from_timestamps:
    step: 0.1
  calc_durations:
    in_seconds: True
    token_level: True
  text:
    type: TextProcessor
    allow_zero_sil: False
    token_level: True


singleton_handlers:
  handlers: [SpeakerIDSetter]
  SpeakerIDSetter: {}

collate:
  type: PausesPredictionCollate

processor:
  type: DataProcessor
  output_collated_only: True
  verbose_logging: False

sampler:
  type:
    train: WeightedSampler
    test: SimpleSampler
  comb_by_len: True
  epoch_size: 15000
  fields_to_compute_weight: [speaker_id]
